version : '3'

services:
  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'setpasswdheree'
    volumes: 
      - ./mysql:/docker-entrypoint-initdb.d/
      - ./mysql/host_address.cnf:/etc/mysql/host_address.cnf
    networks:
      net1:
        ipv4_address: 172.19.0.9
    ports:
      - 3306:3306
  app:
    image: python:3
    volumes:
      - ./testpg:/usr/src/app
    networks:
      net1:
        ipv4_address: 172.19.0.10
    ports:
      - 5000:5000
    command: 
      - /bin/sh
      - -c
      - |
        cd /usr/src/app
        pip install --no-cache-dir -r requirements.txt
        export FLASK_APP=testpg.py
        gunicorn "testpg:app" -b 0.0.0.0:5000
  proxy:
    image: nginxinc/nginx-unprivileged:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
        net1:
          ipv4_address: 172.19.0.11
    ports:
      - 8080:8080
      
networks:
  net1:
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.0/24"
